version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
  web:
    build: ./web
    ports:
      - "8081:80"
    depends_on:
      - api