version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: tasks_api
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__Default=Data Source=/data/app.db
    ports:
      - "8080:8080"
    volumes:
      - api_data:/data
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: tasks_web
    depends_on:
      - api
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  api_data:
